<a href="https://colab.research.google.com/github/habibshirzad/Quantum-Encryptiom/blob/master/thesis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Below you can find 4 different codes for four different operations.
first of all we are accessing our dataset from our device and uploading directly to google colab. after that we import the required libraries in each operation seprately. it is repeatative but it is easier to run the code again and again. this way we dont have to scroll to the top again and again.

first code is simple machine learning model with no excryption.
second one is RSA, third one is quantum resistant and the last one is balanced. which we are using machine learning technques such as scaling and quantum encryption for example  Simulated quantum-resistant encryption like mathemtical reversable transformation.

link to the dataset:
https://www.kaggle.com/datasets/karimkeraani/carscsv

In [ ]:
!pip install scikit-learn pycryptodome


In [1]:
# uploading our dataset from my computer

from google.colab import files
uploaded = files.upload()
import pandas as pd


df = pd.read_csv("cars.csv")


Saving cars.csv to cars.csv


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [4]:
# checking the target value
df['fueltype']

0         gas
1         gas
2         gas
3         gas
4         gas
        ...  
200       gas
201       gas
202       gas
203    diesel
204       gas
Name: fueltype, Length: 205, dtype: object

1 - Without Any Encryption

In [25]:
# importing the libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score

data = pd.read_csv('cars.csv')


# x is independant and y is our dependant feature that we are going to predict.
X = data[[ 'enginesize', 'wheelbase', 'stroke','boreratio']]
y = data['fueltype'].apply(lambda x: 1 if x == 'gas' else 0)

# splitting the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# initializing our model
model = LogisticRegression(max_iter=1000, class_weight='balanced')

# training
model.fit(X_train, y_train)

# predictions
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# results
print(f"Accuracy: {accuracy:.2f}")
print(f"F1 Score: {f1:.2f}")
print()
print("Confusion Matrix:\n")
print(conf_matrix)
print()
print("Classification Report - ML model - Logistic Reg - Without Encryption :")
print(class_report)




Accuracy: 0.89
F1 Score: 0.93

Confusion Matrix:

[[ 5  3]
 [ 4 50]]

Classification Report - ML model - Logistic Reg - Without Encryption :
              precision    recall  f1-score   support

           0       0.56      0.62      0.59         8
           1       0.94      0.93      0.93        54

    accuracy                           0.89        62
   macro avg       0.75      0.78      0.76        62
weighted avg       0.89      0.89      0.89        62



2 - RSA Encryption

In [7]:
# installing required library
!pip install scikit-learn pycryptodome
from Crypto.PublicKey import RSA

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 24.1 MB/s eta 0:00:00


In [44]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
import base64


df = pd.read_csv('cars.csv')

X = df[['enginesize', 'wheelbase', 'stroke', 'boreratio']]  #independent
y = df['fueltype'].apply(lambda x: 1 if x == 'gas' else 0) #dependent


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Generating RSA Encryption key pair
key = RSA.generate(2048)
public_key = key.publickey()
cipher = PKCS1_OAEP.new(public_key)
decipher = PKCS1_OAEP.new(key)

# encrypting every feature's value
def rsa_encrypt(value):
    value_bytes = str(value).encode('utf-8')  # first convert to bytes
    encrypted_value = cipher.encrypt(value_bytes)  # then encrypt the bytes
    return base64.b64encode(encrypted_value).decode('utf-8')  # retruning Base64 and encode the result for readability

# Function to decrypt
def rsa_decrypt(value):
    encrypted_bytes = base64.b64decode(value.encode('utf-8'))  # decode the encrypted value
    decrypted_value = decipher.decrypt(encrypted_bytes)  # Decrypt the bytes
    return float(decrypted_value.decode('utf-8'))  # Convert back to float

X_train_encrypted = X_train.applymap(rsa_encrypt)
X_test_encrypted = X_test.applymap(rsa_encrypt)


X_train_decrypted = X_train_encrypted.applymap(rsa_decrypt)
X_test_decrypted = X_test_encrypted.applymap(rsa_decrypt)


model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_decrypted, y_train)

y_pred = model.predict(X_test_decrypted)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)


# Results using RSA
print(f"Accuracy: {accuracy:.2f}")
print(f"F1 Score: {f1:.2f}")
print()
print("Confusion Matrix:\n")
print(conf_matrix)
print()

print("Classification Report - ML model - Logistic Reg - RSA simulated Encryption :")
print(class_report)


<ipython-input-44-c847da510f0f>:37: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X_train_encrypted = X_train.applymap(rsa_encrypt)
<ipython-input-44-c847da510f0f>:38: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X_test_encrypted = X_test.applymap(rsa_encrypt)
<ipython-input-44-c847da510f0f>:41: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X_train_decrypted = X_train_encrypted.applymap(rsa_decrypt)
<ipython-input-44-c847da510f0f>:42: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  X_test_decrypted = X_test_encrypted.applymap(rsa_decrypt)


Accuracy: 0.89
F1 Score: 0.93

Confusion Matrix:

[[ 5  3]
 [ 4 50]]

Classification Report - ML model - Logistic Reg - RSA simulated Encryption :
              precision    recall  f1-score   support

           0       0.56      0.62      0.59         8
           1       0.94      0.93      0.93        54

    accuracy                           0.89        62
   macro avg       0.75      0.78      0.76        62
weighted avg       0.89      0.89      0.89        62



3 - Lattice Based Encryption

In [42]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score

data = pd.read_csv('cars.csv')


X = data[['enginesize', 'wheelbase', 'stroke', 'boreratio']]
y = data['fueltype'].apply(lambda x: 1 if x == 'gas' else 0)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

def lattice_encrypt(X):
    encryption_factor = np.random.randint(10, 20)  # Simulating the encryption with random noise
    return X + encryption_factor

def lattice_decrypt(X_encrypted):
    encryption_factor = 15
    return X_encrypted - encryption_factor

X_train_encrypted = lattice_encrypt(X_train)
X_test_encrypted = lattice_encrypt(X_test)

X_train_decrypted = lattice_decrypt(X_train_encrypted)
X_test_decrypted = lattice_decrypt(X_test_encrypted)

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_decrypted, y_train)

y_pred = model.predict(X_test_decrypted)

accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)


# Results - Lattice based
print(f"Accuracy: {accuracy:.2f}")
print(f"F1 Score: {f1:.2f}")
print()
print("Confusion Matrix:\n")
print(conf_matrix)
print()

print("Classification Report - ML model - Logistic Reg - Lattice Based simulated Encryption :")
print(class_report)


Accuracy: 0.34
F1 Score: 0.39

Confusion Matrix:

[[ 8  0]
 [41 13]]

Classification Report - ML model - Logistic Reg - Lattice Based simulated Encryption :
              precision    recall  f1-score   support

           0       0.16      1.00      0.28         8
           1       1.00      0.24      0.39        54

    accuracy                           0.34        62
   macro avg       0.58      0.62      0.33        62
weighted avg       0.89      0.34      0.37        62



4 - Balanced Quantum Encrypion and Traditional Algorithms

In [28]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score
from sklearn.preprocessing import StandardScaler

data = pd.read_csv('cars.csv')

X = data[['enginesize', 'wheelbase', 'stroke', 'boreratio']]
y = data['fueltype'].apply(lambda x: 1 if x == 'gas' else 0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Simulated quantum-resistant encryption (reversible mathematical transformation)
def encrypt_features(X):
    encryption_factor = 10
    return X * encryption_factor

def decrypt_features(X_encrypted):
    encryption_factor = 10
    return X_encrypted / encryption_factor

X_train_encrypted = encrypt_features(X_train)
X_test_encrypted = encrypt_features(X_test)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_encrypted)
X_test_scaled = scaler.transform(X_test_encrypted)


X_train_decrypted = decrypt_features(X_train_scaled)
X_test_decrypted = decrypt_features(X_test_scaled)

model = LogisticRegression(max_iter=1000, class_weight='balanced')
model.fit(X_train_decrypted, y_train)

y_pred = model.predict(X_test_decrypted)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Results - balanced
print(f"Accuracy: {accuracy:.2f}")
print(f"F1 Score: {f1:.2f}")
print()
print("Confusion Matrix:\n")
print(conf_matrix)
print()
print("Classification Report - ML model - Logistic Reg - Balanced :")
print(class_report)


Accuracy: 0.77
F1 Score: 0.86

Confusion Matrix:

[[ 5  3]
 [11 43]]

Classification Report - ML model - Logistic Reg - Balanced :
              precision    recall  f1-score   support

           0       0.31      0.62      0.42         8
           1       0.93      0.80      0.86        54

    accuracy                           0.77        62
   macro avg       0.62      0.71      0.64        62
weighted avg       0.85      0.77      0.80        62

